In [1]:
import pandas as pd

## Primer dataset - Beneficiarios FONASA 2023

In [2]:
original1 = False
try:
    with open("../data/originales/Beneficiarios Fonasa 2023.csv", encoding="latin1", errors="ignore") as f:
        df_beneficiarios = pd.read_csv(f, nrows=10000000)
        print("Se cargo la muestra original")
        original1 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_beneficiarios = pd.read_csv("../data/sample/beneficiarios_sample.csv", encoding='latin1')
    print("Se cargo la muestra")

Se cargo la muestra original

In [3]:
df_beneficiarios

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,202312,67843333,Mujer,60 a 69 años,Titular,B,250.001 - 300.000,Chilena,Dependiente,Trabajador Dependiente,De La Araucanía,Loncoche
9999996,202312,83601946,Mujer,60 a 69 años,Titular,D,600.001 - 650.000,Chilena,Pensionado,Pensionado,Metropolitana De Santiago,Las Condes
9999997,202312,72857291,Mujer,70 a 79 años,Titular,B,200.001 - 250.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Constitución
9999998,202312,70322484,Mujer,60 a 69 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Teodoro Schmidt
9999999,202312,67023610,Mujer,50 a 59 años,Titular,B,550.001 - 600.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Arauco

In [4]:
#revisar si tiene valores nulos
df_beneficiarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 12 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_INFORMACION      int64
 1   CÓDIGO_BENEFICIARIO  int64
 2   SEXO                 object
 3   EDAD_TRAMO           object
 4   TITULAR_CARGA        object
 5   TRAMO_FONASA         object
 6   TRAMO_RENTA          object
 7   NACIONALIDAD         object
 8   CARACTERIZACIÓN      object
 9   TIPO_ASEGURADO       object
 10  REGIÓN_BENEFICIARIO  object
 11  COMUNA_BENEFICIARIO  object
dtypes: int64(2), object(10)
memory usage: 915.5+ MB

In [5]:
#eliminar las filas con valores nulos
df_beneficiarios_sin_nulos= df_beneficiarios.dropna()
df_beneficiarios_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 12 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_INFORMACION      int64
 1   CÓDIGO_BENEFICIARIO  int64
 2   SEXO                 object
 3   EDAD_TRAMO           object
 4   TITULAR_CARGA        object
 5   TRAMO_FONASA         object
 6   TRAMO_RENTA          object
 7   NACIONALIDAD         object
 8   CARACTERIZACIÓN      object
 9   TIPO_ASEGURADO       object
 10  REGIÓN_BENEFICIARIO  object
 11  COMUNA_BENEFICIARIO  object
dtypes: int64(2), object(10)
memory usage: 915.5+ MB

In [6]:
#verificar si existen valores duplicados
df_beneficiarios_sin_nulos.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
9999995    False
9999996    False
9999997    False
9999998    False
9999999    False
Length: 10000000, dtype: bool

In [7]:
#eliminar las filas duplicadas
df_beneficiarios_limpio = df_beneficiarios_sin_nulos.drop_duplicates()
df_beneficiarios_limpio.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
9999995    False
9999996    False
9999997    False
9999998    False
9999999    False
Length: 10000000, dtype: bool

In [8]:
df_beneficiarios_limpio

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,202312,67843333,Mujer,60 a 69 años,Titular,B,250.001 - 300.000,Chilena,Dependiente,Trabajador Dependiente,De La Araucanía,Loncoche
9999996,202312,83601946,Mujer,60 a 69 años,Titular,D,600.001 - 650.000,Chilena,Pensionado,Pensionado,Metropolitana De Santiago,Las Condes
9999997,202312,72857291,Mujer,70 a 79 años,Titular,B,200.001 - 250.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Constitución
9999998,202312,70322484,Mujer,60 a 69 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Teodoro Schmidt
9999999,202312,67023610,Mujer,50 a 59 años,Titular,B,550.001 - 600.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Arauco

In [9]:
#guardaremos el dataframe limpio en un archivo csv
if original1 == True:
    df_beneficiarios_limpio.to_csv("../data/beneficiarios_original_limpio.csv", encoding='latin1', index=False)
elif original1 == False:
    df_beneficiarios_limpio.to_csv("../data/sample/beneficiarios_sample_limpio.csv", encoding='latin1', index=False)

## Segundo dataset - Modalidad Libre Elección 2023

In [33]:
original2 = False
try:
    with open("../data/originales/export MLE 2023.csv", encoding="latin1", errors="ignore") as f:
        df_MLE = pd.read_csv(f, nrows=10000000)
        print("Se cargo la muestra original")
        original2 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_MLE = pd.read_csv("../data/sample/export_MLE_sample.csv", encoding="latin1")
    print("Se cargo la muestra")

Se cargo la muestra original

In [34]:
df_MLE.shape

(10000000, 13)

In [35]:
df_MLE

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTRACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,202301,303006,Exámenes De Diagnóstico,Laboratorio Clínico,80142314,B,35 a 39 años,Mujer,Metropolitana De Santiago,Santiago,1.0,2460,5410
9999996,202302,303006,Exámenes De Diagnóstico,Laboratorio Clínico,70094428,D,20 a 24 años,Hombre,De Tarapacá,Iquique,1.0,2460,5410
9999997,202303,306070,Exámenes De Diagnóstico,Laboratorio Clínico,99480216,B,00 a 02 años,Mujer,Metropolitana De Santiago,San Bernardo,1.0,2460,5410
9999998,202307,305029,Exámenes De Diagnóstico,Laboratorio Clínico,98591706,B,00 a 02 años,Mujer,Del Libertador General Bernardo O'Higgins,Rancagua,1.0,2470,5430
9999999,202301,306061,Exámenes De Diagnóstico,Laboratorio Clínico,74516207,B,30 a 34 años,Mujer,De Coquimbo,La Serena,1.0,2470,5450

In [36]:
df_MLE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_EMISION          int64
 1   CODIGO_PRESTACIÓN    int64
 2   DESC_SECCION         object
 3   DESC_ITEM            object
 4   CODIGO_BENEFICIARIO  int64
 5   TRAMO_FONASA         object
 6   EDAD_TRAMO           object
 7   SEXO                 object
 8   REGION_EMISION       object
 9   COMUNA_EMISION       object
 10  PRESTRACIONES        float64
 11  MONTO_FAM            int64
 12  MONTO_COPAGO         int64
dtypes: float64(1), int64(5), object(7)
memory usage: 991.8+ MB

In [37]:
#revisar si tiene valores nulos
df_MLE.isnull().values.any()

np.True_

In [38]:
# ver cuantos valores nulos hay por columna
df_MLE.isnull().sum()

MES_EMISION                0
CODIGO_PRESTACIÓN          0
DESC_SECCION               0
DESC_ITEM                  0
CODIGO_BENEFICIARIO        0
TRAMO_FONASA              29
EDAD_TRAMO                29
SEXO                      29
REGION_EMISION            10
COMUNA_EMISION            10
PRESTRACIONES          21205
MONTO_FAM                  0
MONTO_COPAGO               0
dtype: int64

In [39]:
#eliminar las filas con valores nulos
df_MLE_sin_nulos= df_MLE.dropna()
df_MLE_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9978756 entries, 0 to 9999999
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_EMISION          int64
 1   CODIGO_PRESTACIÓN    int64
 2   DESC_SECCION         object
 3   DESC_ITEM            object
 4   CODIGO_BENEFICIARIO  int64
 5   TRAMO_FONASA         object
 6   EDAD_TRAMO           object
 7   SEXO                 object
 8   REGION_EMISION       object
 9   COMUNA_EMISION       object
 10  PRESTRACIONES        float64
 11  MONTO_FAM            int64
 12  MONTO_COPAGO         int64
dtypes: float64(1), int64(5), object(7)
memory usage: 1.0+ GB

In [40]:
#reviasr si existen valores duplicados
df_MLE_sin_nulos.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
9999995    False
9999996    False
9999997    False
9999998    False
9999999    False
Length: 9978756, dtype: bool

In [41]:
# eliminar las filas duplicadas
df_MLE_limpio = df_MLE_sin_nulos.drop_duplicates()
df_MLE_limpio.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
9999995    False
9999996    False
9999997    False
9999998    False
9999999    False
Length: 9978756, dtype: bool

In [42]:
df_MLE_limpio = df_MLE_limpio.rename(columns={'PRESTRACIONES': 'PRESTACIONES'})

In [43]:
df_MLE_limpio["REGION_EMISION"] = df_MLE_limpio["REGION_EMISION"].replace({"Ñuble": "De Ñuble"})

In [44]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,202301,303006,Exámenes De Diagnóstico,Laboratorio Clínico,80142314,B,35 a 39 años,Mujer,Metropolitana De Santiago,Santiago,1.0,2460,5410
9999996,202302,303006,Exámenes De Diagnóstico,Laboratorio Clínico,70094428,D,20 a 24 años,Hombre,De Tarapacá,Iquique,1.0,2460,5410
9999997,202303,306070,Exámenes De Diagnóstico,Laboratorio Clínico,99480216,B,00 a 02 años,Mujer,Metropolitana De Santiago,San Bernardo,1.0,2460,5410
9999998,202307,305029,Exámenes De Diagnóstico,Laboratorio Clínico,98591706,B,00 a 02 años,Mujer,Del Libertador General Bernardo O'Higgins,Rancagua,1.0,2470,5430
9999999,202301,306061,Exámenes De Diagnóstico,Laboratorio Clínico,74516207,B,30 a 34 años,Mujer,De Coquimbo,La Serena,1.0,2470,5450

In [45]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

## Tercer Dataframe - Presupuestos MLE 2023

In [46]:
codigos_df = pd.read_excel("../data/originales/2 Planilla MLE 2023.xlsx", engine='openpyxl')

In [47]:
# Eliminamos codigos repetidos
codigos_df = codigos_df[~codigos_df["total1"].isin([0])].copy()

# Formateamos codigos a GSSPPP
codigos_df["CODIGO_PRESTACIÓN"] = (
    codigos_df['grupo'].astype(str).str.zfill(1) +
    codigos_df['sub_grupo'].astype(str).str.zfill(2) +
    codigos_df['presta'].astype(str).str.zfill(3)
)
codigos_df = codigos_df.rename(columns={"glosa": "NOMBRE_PRESTACIÓN"})

nombre_codigos = codigos_df[["CODIGO_PRESTACIÓN", "NOMBRE_PRESTACIÓN"]]

In [48]:
print(nombre_codigos['CODIGO_PRESTACIÓN'].duplicated().sum())

0

In [49]:
codigos_df.sample(5)

,secuencia,grupo,sub_grupo,presta,corr,titulo,anes1,anesben1,anes2,anesben2,...,valcir21,valcir22,valcir23,valcir31,valcir32,valcir33,valcir41,valcir42,valcir43,CODIGO_PRESTACIÓN
497,498,3,5,99,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,305099
1978,1979,13,2,36,0,5,64530,32270,83890,51630,...,46545,60509,74472,37236,48407,59578,0,0,0,1302036
794,795,3,8,15,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,308015
252,253,3,1,90,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,301090
3238,3239,19,2,81,0,5,37580,18790,48850,30060,...,30610,39794,48976,0,0,0,0,0,0,1902081

In [50]:
codigos_df.to_csv("../data/Presupuestos_MLE_2023_original_limpio.csv", encoding='latin1', index=False)

**Hacemos merge df_MLE_limpio y nombre_codigos; y añadimos columna "NOMRE_PRESTACION" al df_MLE_limpio**

In [51]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,202301,303006,Exámenes De Diagnóstico,Laboratorio Clínico,80142314,B,35 a 39 años,Mujer,Metropolitana De Santiago,Santiago,1.0,2460,5410
9999996,202302,303006,Exámenes De Diagnóstico,Laboratorio Clínico,70094428,D,20 a 24 años,Hombre,De Tarapacá,Iquique,1.0,2460,5410
9999997,202303,306070,Exámenes De Diagnóstico,Laboratorio Clínico,99480216,B,00 a 02 años,Mujer,Metropolitana De Santiago,San Bernardo,1.0,2460,5410
9999998,202307,305029,Exámenes De Diagnóstico,Laboratorio Clínico,98591706,B,00 a 02 años,Mujer,Del Libertador General Bernardo O'Higgins,Rancagua,1.0,2470,5430
9999999,202301,306061,Exámenes De Diagnóstico,Laboratorio Clínico,74516207,B,30 a 34 años,Mujer,De Coquimbo,La Serena,1.0,2470,5450

In [52]:
df_MLE_limpio['CODIGO_PRESTACIÓN'] = df_MLE_limpio['CODIGO_PRESTACIÓN'].astype(str)
nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

df_MLE_limpio = df_MLE_limpio.merge(nombre_codigos, left_on="CODIGO_PRESTACIÓN", right_on="CODIGO_PRESTACIÓN", how='left')

C:\Users\benja\AppData\Local\Temp\ipykernel_2604\142898981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

In [53]:
df_MLE_limpio.sample(5)

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
9240026,202302,305070,Exámenes De Diagnóstico,Laboratorio Clínico,78631785,B,60 a 64 años,Hombre,De Los Lagos,Puerto Montt,2.0,8020,17680,ANTIGENO PROSTATICO ESPECIFICO ...
3063645,202307,101310,Atención Médica,Consulta Médica,75392412,C,50 a 54 años,Mujer,Metropolitana De Santiago,Providencia,2.0,21020,14020,CONSULTA MEDICA DE ESPECIALIDAD EN TRAUMATOLOG...
3605221,202302,303026,Exámenes De Diagnóstico,Laboratorio Clínico,81160205,D,45 a 49 años,Hombre,De Arica Y Parinacota,Arica,1.0,2290,5050,TIROXINA LIBRE (T4L) ...
9655043,202301,101310,Atención Médica,Consulta Médica,97283099,B,15 a 19 años,Mujer,Metropolitana De Santiago,Providencia,1.0,9890,6590,CONSULTA MEDICA DE ESPECIALIDAD EN TRAUMATOLOG...
7191914,202309,2501059,Pad,"Gastroenterología, Coloproctología, Cirugía Di...",71591234,D,30 a 34 años,Mujer,Del Maule,Talca,1.0,2612260,2612270,"CIRUGIA BARIATRICA POR MANGA GASTRICA, INCLUYE..."

In [54]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

In [55]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900,"ORINA COMPLETA, (INCLUYE COD. 03-09-023 Y 03-0..."
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390,CREATININA EN SANGRE ...
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390,CREATININA EN SANGRE ...
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390,CREATININA EN SANGRE ...
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390,CREATININA EN SANGRE ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9978751,202301,303006,Exámenes De Diagnóstico,Laboratorio Clínico,80142314,B,35 a 39 años,Mujer,Metropolitana De Santiago,Santiago,1.0,2460,5410,CORTISOL ...
9978752,202302,303006,Exámenes De Diagnóstico,Laboratorio Clínico,70094428,D,20 a 24 años,Hombre,De Tarapacá,Iquique,1.0,2460,5410,CORTISOL ...
9978753,202303,306070,Exámenes De Diagnóstico,Laboratorio Clínico,99480216,B,00 a 02 años,Mujer,Metropolitana De Santiago,San Bernardo,1.0,2460,5410,"ANTIGENOS VIRALES DETERM. DE (ADENOVIRUS, CITO..."
9978754,202307,305029,Exámenes De Diagnóstico,Laboratorio Clínico,98591706,B,00 a 02 años,Mujer,Del Libertador General Bernardo O'Higgins,Rancagua,1.0,2470,5430,"INMUNOGLOBULINAS IGE, IGG ESPECIFICAS, C/U ..."
9978755,202301,306061,Exámenes De Diagnóstico,Laboratorio Clínico,74516207,B,30 a 34 años,Mujer,De Coquimbo,La Serena,1.0,2470,5450,"PARASITOS IGG/IGM (CHAGAS, HIDATIDOSIS, TOXOCA..."